### ISSUE TITLE
The image cannot be centered and cannot upload the same image

### ISSUE THREAD

**Issue by yingchy1996** [wfpena/angular-wysiwyg#28] opened 2024-07-16 05:43 UTC
I look the center tag is on the image instead of the div, and I look the image in the demo is centered on the div
![1721108442286](https://github.com/user-attachments/assets/266c08e6-3ed1-45a6-9f0a-48fb9bd26350)
![1721108581848](https://github.com/user-attachments/assets/0bb30ae6-236d-4e27-9e7d-052a0ae8ab3f)

**Comment by yingchy1996** [comment] 2024-07-16 10:32
If you upload one Image(name: 111) and delete it, zhen upload the same image(name: 111), you cannot insert it more!!!

**Comment by yingchy1996** [comment] 2024-07-16 10:45
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.07.16-18_44_12.webm](https://github.com/user-attachments/assets/8ef1dbde-8815-4db5-8d56-fe47d2b07e1f)

**Comment by wfpena** [comment] 2024-07-18 12:28
@yingchy1996 I opened a PR to fix the issue, will try to deploy a new version today with it https://github.com/wfpena/angular-wysiwyg/pull/29

**Comment by wfpena** [comment] 2024-07-18 12:28
@yingchy1996  also, I was not able to reproduce the centering issue, I think you are clicking on the side of the image and not the image itself on the first case.

**Comment by wfpena** [comment] 2024-07-18 13:04
@yingchy1996 published the fix, let me know if we can close this or you want another check at the centering issue.

**Comment by yingchy1996** [comment] 2024-07-19 02:10
@wfpena the image cannot upload again is ok. And the image cannot be center, it looks my problem, i see when i click the center-btn, the console show likes the flower image. Oh my weak English, I hope you can understand it，Can you give me some solutions, thanks
![30569](https://github.com/user-attachments/assets/e0772ca8-ce4d-416f-8569-47d892fb9713)

**Comment by yingchy1996** [comment] 2024-07-19 02:28
https://github.com/user-attachments/assets/1efe7963-999c-47d5-a659-8083787f48aa

**Comment by wfpena** [comment] 2024-07-19 11:44
@yingchy1996 I don't think the issue is on that warning about sanitizing. For you to check you can pass the `sanitize: false` config to the component.

I tested here and was not able to reproduce. At first thought you should initially double check 3 things:
1. Disable sanitize to make sure it isn't the issue (passing the config as mentioned `sanitize: false`)
2. Make sure you have the latest version of this component (could you be running an outdated version on your project?)
3. Make sure there are no styles on the image that are overriding its position somehow

**Comment by wfpena** [comment] 2024-07-20 11:49
Closing this issue since this PR https://github.com/wfpena/angular-wysiwyg/pull/29 solves it.

@yingchy1996 we can still check the problem that you are having, but closing the issue itself since the bug is fixed.

**Closed by wfpena** 2024-07-20 11:49 UTC
Labels: bug

**Comment by yingchy1996** [comment] 2024-07-23 03:10
Thanks

**Comment by yingchy1996** [comment] 2024-08-30 07:40
The reason why the image can't be center is the tailwind effect the editor
Use the code can resolve the problem
`
@layer base {
angular-editor *:not(img) {
    all: revert;
  }
}`

**Comment by seb128s** [comment] 2025-02-20 16:23
I would like to add this to the solution if you are using tailwind.
You must use the yingchy1996's solution and add this : angular-editor img { display: revert; }
and resize and align work fine
